import { nexSubject } from "@/components/types";

export const nexIctSubjects: nexSubject[] = [
  {
    id: "sub_01",
    title: "Introduction to Programming",
    description: "Fundamentals of coding using languages like C and Python, covering variables, loops, and logic.",
    slug: "introduction-to-programming",
    departmentID: "dep_ict_main",
    academicYear: 1,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-15T09:00:00Z",
    updatedAt: "2023-08-15T09:00:00Z",
  },
  {
    id: "sub_02",
    title: "Data Communication & Networking",
    description: "An overview of network topologies, the OSI model, TCP/IP protocols, and modern wireless communication.",
    slug: "data-communication-and-networking",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-16T10:30:00Z",
    updatedAt: "2023-09-01T14:20:00Z",
  },
  {
    id: "sub_03",
    title: "Database Management Systems",
    description: "Core concepts of relational databases, SQL querying, normalization, and NoSQL alternatives.",
    slug: "database-management-systems",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-17T11:00:00Z",
    updatedAt: "2023-08-17T11:00:00Z",
  },
  {
    id: "sub_04",
    title: "Web Technologies",
    description: "Building dynamic websites using HTML, CSS, JavaScript, and modern frameworks like Next.js.",
    slug: "web-technologies",
    departmentID: "dep_ict_main",
    academicYear: 1,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-18T09:15:00Z",
    updatedAt: "2023-10-12T16:45:00Z",
  },
  {
    id: "sub_05",
    title: "Cybersecurity Essentials",
    description: "Principles of information security, threat analysis, cryptography, and secure network design.",
    slug: "cybersecurity-essentials",
    departmentID: "dep_ict_sec",
    academicYear: 3,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-19T13:00:00Z",
    updatedAt: "2023-08-19T13:00:00Z",
  },
  {
    id: "sub_06",
    title: "Operating Systems",
    description: "Understanding process management, memory allocation, file systems, and virtualization.",
    slug: "operating-systems",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-20T08:45:00Z",
    updatedAt: "2023-08-20T08:45:00Z",
  },
  {
    id: "sub_07",
    title: "Cloud Computing",
    description: "Introduction to cloud services (IaaS, PaaS, SaaS) and platforms like AWS and Azure.",
    slug: "cloud-computing",
    departmentID: "dep_ict_main",
    academicYear: 3,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-21T14:10:00Z",
    updatedAt: "2023-11-05T09:30:00Z",
  },
  {
    id: "sub_08",
    title: "Data Structures and Algorithms",
    description: "Advanced problem solving using arrays, linked lists, trees, graphs, and sorting algorithms.",
    slug: "data-structures-and-algorithms",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-22T10:00:00Z",
    updatedAt: "2023-08-22T10:00:00Z",
  },
  {
    id: "sub_09",
    title: "Artificial Intelligence",
    description: "Basics of AI, machine learning models, neural networks, and ethical considerations in AI.",
    slug: "artificial-intelligence",
    departmentID: "dep_ict_ds",
    academicYear: 4,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-23T15:20:00Z",
    updatedAt: "2023-08-23T15:20:00Z",
  },
  {
    id: "sub_10",
    title: "Software Engineering",
    description: "The software development lifecycle (SDLC), agile methodologies, testing, and project management.",
    slug: "software-engineering",
    departmentID: "dep_ict_se",
    academicYear: 3,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-24T12:00:00Z",
    updatedAt: "2023-09-15T11:00:00Z",
  },
  {
    id: "sub_11",
    title: "Mobile Application Development",
    description: "Designing and building applications for Android and iOS using Flutter, React Native, or Swift.",
    slug: "mobile-application-development",
    departmentID: "dep_ict_se",
    academicYear: 3,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-25T09:00:00Z",
    updatedAt: "2023-09-20T14:00:00Z",
  },
  {
    id: "sub_12",
    title: "Internet of Things (IoT)",
    description: "Connecting physical devices to the internet using sensors, microcontrollers (Arduino/Raspberry Pi), and communication protocols.",
    slug: "internet-of-things",
    departmentID: "dep_ict_eng",
    academicYear: 4,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-26T10:30:00Z",
    updatedAt: "2023-08-26T10:30:00Z",
  },
  {
    id: "sub_13",
    title: "Human-Computer Interaction",
    description: "Study of UI/UX design principles, usability testing, and accessibility standards for software interfaces.",
    slug: "human-computer-interaction",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-27T11:15:00Z",
    updatedAt: "2023-10-05T09:45:00Z",
  },
  {
    id: "sub_14",
    title: "Data Science and Analytics",
    description: "Extracting insights from large datasets using statistical analysis, data mining, and visualization tools.",
    slug: "data-science-and-analytics",
    departmentID: "dep_ict_ds",
    academicYear: 4,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-28T13:00:00Z",
    updatedAt: "2023-08-28T13:00:00Z",
  },
  {
    id: "sub_15",
    title: "Computer Graphics and Multimedia",
    description: "Fundamentals of 2D/3D rendering, image processing, animation, and multimedia file formats.",
    slug: "computer-graphics-and-multimedia",
    departmentID: "dep_ict_main",
    academicYear: 2,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-29T08:30:00Z",
    updatedAt: "2023-08-29T08:30:00Z",
  },
  {
    id: "sub_16",
    title: "Systems Analysis and Design",
    description: "Methodologies for analyzing business requirements and designing scalable information systems.",
    slug: "systems-analysis-and-design",
    departmentID: "dep_ict_main",
    academicYear: 3,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-30T14:45:00Z",
    updatedAt: "2023-09-12T16:20:00Z",
  },
  {
    id: "sub_17",
    title: "Digital Forensics",
    description: "Techniques for recovering, analyzing, and preserving digital evidence for legal investigations.",
    slug: "digital-forensics",
    departmentID: "dep_ict_sec",
    academicYear: 4,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-08-31T09:10:00Z",
    updatedAt: "2023-08-31T09:10:00Z",
  },
  {
    id: "sub_18",
    title: "Blockchain Technology",
    description: "Understanding decentralized ledgers, smart contracts, cryptocurrencies, and consensus algorithms.",
    slug: "blockchain-technology",
    departmentID: "dep_ict_eng",
    academicYear: 4,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-01T15:30:00Z",
    updatedAt: "2023-11-10T11:00:00Z",
  },
  {
    id: "sub_19",
    title: "DevOps and Site Reliability",
    description: "Bridging development and operations using CI/CD pipelines, containerization (Docker), and orchestration (Kubernetes).",
    slug: "devops-and-site-reliability",
    departmentID: "dep_ict_se",
    academicYear: 4,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-02T10:00:00Z",
    updatedAt: "2023-09-02T10:00:00Z",
  },
  {
    id: "sub_20",
    title: "Computer Architecture",
    description: "The internal structure of computers, including CPU design, assembly language, and memory hierarchy.",
    slug: "computer-architecture",
    departmentID: "dep_ict_eng",
    academicYear: 1,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-03T12:20:00Z",
    updatedAt: "2023-09-03T12:20:00Z",
  },
  {
    id: "sub_21",
    title: "Enterprise Resource Planning",
    description: "Implementation and management of integrated business software suites like SAP or Oracle ERP.",
    slug: "enterprise-resource-planning",
    departmentID: "dep_ict_biz",
    academicYear: 3,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-04T08:00:00Z",
    updatedAt: "2023-10-01T13:15:00Z",
  },
  {
    id: "sub_22",
    title: "Game Development",
    description: "Creating interactive video games using engines like Unity or Unreal, covering physics, audio, and scripting.",
    slug: "game-development",
    departmentID: "dep_ict_se",
    academicYear: 3,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-05T16:00:00Z",
    updatedAt: "2023-09-05T16:00:00Z",
  },
  {
    id: "sub_23",
    title: "IT Law and Ethics",
    description: "Legal frameworks governing IT, intellectual property rights, data privacy laws (GDPR), and professional ethics.",
    slug: "it-law-and-ethics",
    departmentID: "dep_ict_main",
    academicYear: 4,
    semester: 2,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-06T09:30:00Z",
    updatedAt: "2023-09-06T09:30:00Z",
  },
  {
    id: "sub_24",
    title: "Management Information Systems",
    description: "The use of computer systems to manage organizations, including decision support systems and strategic IT planning.",
    slug: "management-information-systems",
    departmentID: "dep_ict_biz",
    academicYear: 3,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-07T11:45:00Z",
    updatedAt: "2023-09-25T10:30:00Z",
  },
  {
    id: "sub_25",
    title: "Parallel and Distributed Computing",
    description: "Computing systems that run on multiple processors or networked computers to solve complex problems.",
    slug: "parallel-and-distributed-computing",
    departmentID: "dep_ict_eng",
    academicYear: 4,
    semester: 1,
    createdBy: "usr_root_001",
    createdByRole: "nexRoot",
    isOfficial: true,
    createdAt: "2023-09-08T14:10:00Z",
    updatedAt: "2023-09-08T14:10:00Z",
  },
];