import { Note_Item } from "@/components/types";

export const Suggestion_dataset: Note_Item = [
  { id: "fav-1", title: "Smart Database", imgUrl: "/img/sub/test/001.jpg" },
  { id: "fav-2", title: "NextGen Network", imgUrl: "/img/sub/test/002.jpg" },
  { id: "fav-3", title: "Dynamic AI", imgUrl: "/img/sub/test/003.jpg" },
  { id: "fav-4", title: "Integrated Security", imgUrl: "/img/sub/test/004.jpg" },
  { id: "fav-5", title: "Innovative Cloud", imgUrl: "/img/sub/test/005.jpg" },
  { id: "fav-6", title: "Advanced Software", imgUrl: "/img/sub/test/006.jpg" },
  { id: "fav-7", title: "Efficient App", imgUrl: "/img/sub/test/007.jpg" },
  { id: "fav-8", title: "Rapid Service", imgUrl: "/img/sub/test/008.jpg" },
  { id: "fav-9", title: "Modern Design", imgUrl: "/img/sub/test/009.jpg" },
  { id: "fav-10", title: "Virtual System", imgUrl: "/img/sub/test/010.jpg" },
  { id: "fav-11", title: "NextGen Software", imgUrl: "/img/sub/test/001.jpg" },
  { id: "fav-12", title: "Dynamic Security", imgUrl: "/img/sub/test/002.jpg" },
  { id: "fav-13", title: "Smart Cloud", imgUrl: "/img/sub/test/003.jpg" },
  { id: "fav-14", title: "Integrated App", imgUrl: "/img/sub/test/004.jpg" },
  { id: "fav-15", title: "Innovative System", imgUrl: "/img/sub/test/005.jpg" },
  { id: "fav-16", title: "Efficient AI", imgUrl: "/img/sub/test/006.jpg" },
  { id: "fav-17", title: "Advanced Design", imgUrl: "/img/sub/test/007.jpg" },
  { id: "fav-18", title: "Rapid Network", imgUrl: "/img/sub/test/008.jpg" },
  { id: "fav-19", title: "Virtual Service", imgUrl: "/img/sub/test/009.jpg" },
  { id: "fav-20", title: "Modern Database", imgUrl: "/img/sub/test/010.jpg" },
  { id: "fav-21", title: "Smart App", imgUrl: "/img/sub/test/001.jpg" },
  { id: "fav-22", title: "NextGen AI", imgUrl: "/img/sub/test/002.jpg" },
  { id: "fav-23", title: "Dynamic Cloud", imgUrl: "/img/sub/test/003.jpg" },
  { id: "fav-24", title: "Integrated Service", imgUrl: "/img/sub/test/004.jpg" },
  { id: "fav-25", title: "Innovative Network", imgUrl: "/img/sub/test/005.jpg" },
  { id: "fav-26", title: "Advanced System", imgUrl: "/img/sub/test/006.jpg" },
  { id: "fav-27", title: "Efficient Design", imgUrl: "/img/sub/test/007.jpg" },
  { id: "fav-28", title: "Rapid Software", imgUrl: "/img/sub/test/008.jpg" },
  { id: "fav-29", title: "Virtual Database", imgUrl: "/img/sub/test/009.jpg" },
  { id: "fav-30", title: "Modern Cloud", imgUrl: "/img/sub/test/010.jpg" },
];
